/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package email;

public class App {

    private static String emailHost = ""; // find this on your email providers smtp page
    private static String port = ""; // find this on your email prodivers smtp page
    private static String emailFrom = ""; // your email address
    private static String emailPassword = ""; // email password (you may need an app specific one if you
                                              // have 2fa)
    private static String emailTo = ""; // recieving email
    private static String subject = ""; //
    private static String body = "";

    public static void main(String[] args) {
        sendEmail();
    }

    private static void sendEmail() {
        Email e = new Email(emailHost, port, emailFrom, emailPassword, emailTo, subject, body);
        e.sendEmail();
        System.out.println(("email sent"));

    }
}
